#!/usr/bin/env bash
# Builds and (re)deploys the staging demo from the checked-out source.
#
#   sudo DOMAIN=api.example.com ./deploy.sh            # deploy, keep data
#   sudo DOMAIN=api.example.com RESEED=1 ./deploy.sh   # deploy, rebuild demo schools
#
# Run from a checkout of the repository on the server. On the first run it
# creates /opt/cyberschola/staging.env with fresh random database passwords;
# after that it reuses them. The file is readable by root only.
set -euo pipefail

DOMAIN="${DOMAIN:?DOMAIN is required, such as api.example.com}"
HERE="$(cd "$(dirname "$0")" && pwd)"
BACKEND="$(cd "$HERE/../.." && pwd)"
ENV_FILE=/opt/cyberschola/staging.env
COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$HERE/docker-compose.yml")

echo "== configuration"
if [ ! -f "$ENV_FILE" ]; then
  install -d -m 700 /opt/cyberschola
  owner_password="$(openssl rand -hex 24)"
  app_password="$(openssl rand -hex 24)"
  umask 077
  cat > "$ENV_FILE" <<ENV
# CyberSchola staging. Generated by deploy.sh; root-only.
POSTGRES_PASSWORD=${owner_password}
APP_DB_PASSWORD=${app_password}
# The API connects as the restricted role, so row-level security applies.
DATABASE_URL=postgres://cyberschola_app:${app_password}@postgres:5432/cyberschola
# Migrations and the demo seed connect as the owner.
DIRECT_URL=postgres://cyberschola:${owner_password}@postgres:5432/cyberschola
DATABASE_SSL=false
REDIS_URL=redis://redis:6379
# The staging demo sign-in. Production refuses any issuer that is not Supabase.
SUPABASE_URL=https://${DOMAIN}/demo-auth
SUPABASE_JWKS_URL=https://${DOMAIN}/demo-auth/jwks.json
DEMO_AUTH_ISSUER_BASE=https://${DOMAIN}/demo-auth
CORS_ORIGINS=
ENV
  first_run=1
else
  first_run=0
fi
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

echo "== image"
docker build -t cyberschola-api:staging "$BACKEND"

echo "== database"
"${COMPOSE[@]}" up -d postgres redis
"${COMPOSE[@]}" --profile tasks run --rm migrate
# The application role is created by a migration without a password; give it
# this server's. Passed on stdin, so it never appears in a process listing.
printf "ALTER ROLE cyberschola_app WITH PASSWORD '%s';\n" "$APP_DB_PASSWORD" \
  | "${COMPOSE[@]}" exec -T postgres psql -q -U cyberschola -d cyberschola -v ON_ERROR_STOP=1

if [ "$first_run" = 1 ] || [ "${RESEED:-0}" = 1 ]; then
  echo "== demo schools"
  "${COMPOSE[@]}" --profile tasks run --rm seed
fi

echo "== services"
"${COMPOSE[@]}" up -d api demo-auth

for attempt in $(seq 1 40); do
  if curl -fsS http://127.0.0.1:3000/api/v1/health >/dev/null 2>&1; then
    echo "== healthy: https://${DOMAIN}/api/docs"
    exit 0
  fi
  sleep 3
done

echo "The API did not become healthy. Last log lines:" >&2
"${COMPOSE[@]}" logs --tail 60 api >&2
exit 1
