import {
  Body,
  Controller,
  Delete,
  Get,
  HttpStatus,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  Put,
  Query,
} from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';

import { Permission } from '../auth/permission.matrix';
import { RequiresPermission } from '../auth/requires-permission.decorator';
import { type Page, PaginationQueryDto, toPageRequest } from '../common/pagination/pagination';
import {
  ApiEmptyResponse,
  ApiErrorResponse,
  ApiItemResponse,
  ApiPageResponse,
} from '../common/swagger/api-responses';
import {
  CreateGuardianshipDto,
  CreateParentDto,
  CreateSchoolAdminDto,
  CreateStaffDto,
  CreateStudentDto,
  CreateTeacherDto,
  GuardianshipDto,
  GuardianshipQueryDto,
  LinkAccountDto,
  ParentDto,
  SchoolAdminDto,
  StaffDto,
  StudentDto,
  TeacherDto,
  UpdateParentDto,
  UpdateStaffDto,
  UpdateStudentDto,
  UpdateTeacherDto,
} from './people.dto';
import { LAST_ADMINISTRATOR_MESSAGE, PERSON_KINDS, PeopleService } from './people.service';

const BODY_INVALID = 'The body failed validation.';
const NOT_IN_SCHOOL = (what: string) => `No ${what} with this id in this school.`;
const LINK_NOT_FOUND = (what: string) =>
  `No ${what}, or no membership, with that id in this school.`;
const ALREADY_LINKED = (what: string) =>
  `That membership is already linked to another ${what} in this school.`;

/*
 * One controller per person type, each thin, all delegating to PeopleService.
 *
 * Written out rather than generated by a factory on purpose. A generic controller
 * erases the body type at runtime, and the global ValidationPipe reads the body's
 * class from that type metadata: a factory-built route would silently skip
 * validation. The shared behaviour lives in the service, where generics cost
 * nothing, and these stay explicit so every route is visible to the conformance
 * gate and to a reviewer.
 */

@ApiTags('People')
@Controller('students')
export class StudentsController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.StudentRead)
  @ApiOperation({
    summary: 'Students this caller may see',
    description:
      'An administrator sees every student. A teacher sees students in a class they supervise ' +
      'this session, or taking a subject they teach (electives only when registered). A parent ' +
      'sees their linked children. A student sees themselves. A person holding several roles ' +
      'sees the union. Each item is `summary` or `profile`: see `view`. The total follows the ' +
      'same scope.',
  })
  @ApiPageResponse(StudentDto, 'Students retrieved.')
  list(@Query() query: PaginationQueryDto): Promise<Page<StudentDto>> {
    return this.people.listStudents(toPageRequest(query));
  }

  @Get(':id')
  @RequiresPermission(Permission.StudentRead)
  @ApiOperation({
    summary: 'One student',
    description:
      'Under the same scope as the list. A student this caller may not see is 404, identical ' +
      'to an id that does not exist, so a parent cannot learn whether another child is enrolled.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, 'No student with this id that this caller may see.')
  @ApiItemResponse(StudentDto, 'Student retrieved.')
  get(@Param('id', ParseUUIDPipe) id: string): Promise<StudentDto> {
    return this.people.getStudent(id);
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Create a student record',
    description: 'Created without a login. Link one with PUT /students/{id}/account.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.CONFLICT, 'The admission number is already used in this school.')
  @ApiItemResponse(StudentDto, 'Student created.', HttpStatus.CREATED)
  create(@Body() input: CreateStudentDto): Promise<StudentDto> {
    return this.people.create(PERSON_KINDS.student, input);
  }

  @Patch(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Update a student record' })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('student'))
  @ApiErrorResponse(HttpStatus.CONFLICT, 'The admission number is already used in this school.')
  @ApiItemResponse(StudentDto, 'Student updated.')
  update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() input: UpdateStudentDto,
  ): Promise<StudentDto> {
    return this.people.update(PERSON_KINDS.student, id, input);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Remove a student record',
    description:
      'Soft delete. Enrolments and guardianships keep their history, and the admission number ' +
      'becomes free to reuse.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('student'))
  @ApiEmptyResponse('Student removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.remove(PERSON_KINDS.student, id);
  }

  @Put(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Link a login to a student's record",
    description: 'Gives that membership the STUDENT role in this school.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, LINK_NOT_FOUND('student'))
  @ApiErrorResponse(HttpStatus.CONFLICT, ALREADY_LINKED('student'))
  @ApiItemResponse(StudentDto, 'Account linked.')
  link(@Param('id', ParseUUIDPipe) id: string, @Body() input: LinkAccountDto): Promise<StudentDto> {
    return this.people.linkAccount(PERSON_KINDS.student, id, input.membershipId);
  }

  @Delete(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Unlink a student's login",
    description: 'Removes the STUDENT role from that membership. The record stays.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('student'))
  @ApiItemResponse(StudentDto, 'Account unlinked.')
  unlink(@Param('id', ParseUUIDPipe) id: string): Promise<StudentDto> {
    return this.people.unlinkAccount(PERSON_KINDS.student, id);
  }
}

@ApiTags('People')
@Controller('teachers')
export class TeachersController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Teachers' })
  @ApiPageResponse(TeacherDto, 'Teachers retrieved.')
  list(@Query() query: PaginationQueryDto): Promise<Page<TeacherDto>> {
    return this.people.list(PERSON_KINDS.teacher, toPageRequest(query));
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Create a teacher record',
    description: 'Created without a login. Link one with PUT /teachers/{id}/account.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiItemResponse(TeacherDto, 'Teacher created.', HttpStatus.CREATED)
  create(@Body() input: CreateTeacherDto): Promise<TeacherDto> {
    return this.people.create(PERSON_KINDS.teacher, input);
  }

  @Patch(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Update a teacher record' })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('teacher'))
  @ApiItemResponse(TeacherDto, 'Teacher updated.')
  update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() input: UpdateTeacherDto,
  ): Promise<TeacherDto> {
    return this.people.update(PERSON_KINDS.teacher, id, input);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Remove a teacher record',
    description: 'Soft delete. Their assignments stop granting access to any student at once.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('teacher'))
  @ApiEmptyResponse('Teacher removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.remove(PERSON_KINDS.teacher, id);
  }

  @Put(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Link a login to a teacher's record",
    description: 'Gives that membership the TEACHER role in this school.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, LINK_NOT_FOUND('teacher'))
  @ApiErrorResponse(HttpStatus.CONFLICT, ALREADY_LINKED('teacher'))
  @ApiItemResponse(TeacherDto, 'Account linked.')
  link(@Param('id', ParseUUIDPipe) id: string, @Body() input: LinkAccountDto): Promise<TeacherDto> {
    return this.people.linkAccount(PERSON_KINDS.teacher, id, input.membershipId);
  }

  @Delete(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Unlink a teacher's login",
    description: 'Removes the TEACHER role from that membership. The record stays.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('teacher'))
  @ApiItemResponse(TeacherDto, 'Account unlinked.')
  unlink(@Param('id', ParseUUIDPipe) id: string): Promise<TeacherDto> {
    return this.people.unlinkAccount(PERSON_KINDS.teacher, id);
  }
}

@ApiTags('People')
@Controller('parents')
export class ParentsController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Parents' })
  @ApiPageResponse(ParentDto, 'Parents retrieved.')
  list(@Query() query: PaginationQueryDto): Promise<Page<ParentDto>> {
    return this.people.list(PERSON_KINDS.parent, toPageRequest(query));
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Create a parent record',
    description:
      'Created without a login and without children. Link a login with PUT ' +
      '/parents/{id}/account, and children with POST /guardianships.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiItemResponse(ParentDto, 'Parent created.', HttpStatus.CREATED)
  create(@Body() input: CreateParentDto): Promise<ParentDto> {
    return this.people.create(PERSON_KINDS.parent, input);
  }

  @Patch(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Update a parent record' })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('parent'))
  @ApiItemResponse(ParentDto, 'Parent updated.')
  update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() input: UpdateParentDto,
  ): Promise<ParentDto> {
    return this.people.update(PERSON_KINDS.parent, id, input);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Remove a parent record',
    description: 'Soft delete. The parent loses access to every linked child at once.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('parent'))
  @ApiEmptyResponse('Parent removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.remove(PERSON_KINDS.parent, id);
  }

  @Put(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Link a login to a parent's record",
    description: 'Gives that membership the PARENT role in this school.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, LINK_NOT_FOUND('parent'))
  @ApiErrorResponse(HttpStatus.CONFLICT, ALREADY_LINKED('parent'))
  @ApiItemResponse(ParentDto, 'Account linked.')
  link(@Param('id', ParseUUIDPipe) id: string, @Body() input: LinkAccountDto): Promise<ParentDto> {
    return this.people.linkAccount(PERSON_KINDS.parent, id, input.membershipId);
  }

  @Delete(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Unlink a parent's login",
    description: 'Removes the PARENT role from that membership. The record stays.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('parent'))
  @ApiItemResponse(ParentDto, 'Account unlinked.')
  unlink(@Param('id', ParseUUIDPipe) id: string): Promise<ParentDto> {
    return this.people.unlinkAccount(PERSON_KINDS.parent, id);
  }
}

@ApiTags('People')
@Controller('staff')
export class StaffController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Staff' })
  @ApiPageResponse(StaffDto, 'Staff retrieved.')
  list(@Query() query: PaginationQueryDto): Promise<Page<StaffDto>> {
    return this.people.list(PERSON_KINDS.staff, toPageRequest(query));
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Create a staff record',
    description: 'Created without a login. Link one with PUT /staff/{id}/account.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiItemResponse(StaffDto, 'Staff member created.', HttpStatus.CREATED)
  create(@Body() input: CreateStaffDto): Promise<StaffDto> {
    return this.people.create(PERSON_KINDS.staff, input);
  }

  @Patch(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Update a staff record' })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('staff member'))
  @ApiItemResponse(StaffDto, 'Staff member updated.')
  update(@Param('id', ParseUUIDPipe) id: string, @Body() input: UpdateStaffDto): Promise<StaffDto> {
    return this.people.update(PERSON_KINDS.staff, id, input);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Remove a staff record', description: 'Soft delete.' })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('staff member'))
  @ApiEmptyResponse('Staff member removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.remove(PERSON_KINDS.staff, id);
  }

  @Put(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Link a login to a staff member's record",
    description: 'Gives that membership the STAFF role in this school.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, LINK_NOT_FOUND('staff member'))
  @ApiErrorResponse(HttpStatus.CONFLICT, ALREADY_LINKED('staff member'))
  @ApiItemResponse(StaffDto, 'Account linked.')
  link(@Param('id', ParseUUIDPipe) id: string, @Body() input: LinkAccountDto): Promise<StaffDto> {
    return this.people.linkAccount(PERSON_KINDS.staff, id, input.membershipId);
  }

  @Delete(':id/account')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: "Unlink a staff member's login",
    description: 'Removes the STAFF role from that membership. The record stays.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('staff member'))
  @ApiItemResponse(StaffDto, 'Account unlinked.')
  unlink(@Param('id', ParseUUIDPipe) id: string): Promise<StaffDto> {
    return this.people.unlinkAccount(PERSON_KINDS.staff, id);
  }
}

@ApiTags('People')
@Controller('school-admins')
export class SchoolAdminsController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'School administrators' })
  @ApiPageResponse(SchoolAdminDto, 'Administrators retrieved.')
  list(@Query() query: PaginationQueryDto): Promise<Page<SchoolAdminDto>> {
    return this.people.listAdmins(toPageRequest(query));
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Make a member an administrator',
    description: 'Gives that membership the SCHOOL_ADMIN role in this school.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('membership'))
  @ApiErrorResponse(HttpStatus.CONFLICT, 'That membership is already an administrator.')
  @ApiItemResponse(SchoolAdminDto, 'Administrator added.', HttpStatus.CREATED)
  create(@Body() input: CreateSchoolAdminDto): Promise<SchoolAdminDto> {
    return this.people.addAdmin(input.membershipId);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Remove an administrator',
    description:
      'The last administrator cannot be removed (409), because nobody would be left who could ' +
      'add one back. Holds under concurrent removals.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('administrator'))
  @ApiErrorResponse(
    HttpStatus.CONFLICT,
    'This is the last administrator of the school.',
    LAST_ADMINISTRATOR_MESSAGE,
  )
  @ApiEmptyResponse('Administrator removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.removeAdmin(id);
  }
}

@ApiTags('People')
@Controller('guardianships')
export class GuardianshipsController {
  constructor(private readonly people: PeopleService) {}

  @Get()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({ summary: 'Links between parents and children' })
  @ApiPageResponse(GuardianshipDto, 'Guardianships retrieved.')
  list(@Query() query: GuardianshipQueryDto): Promise<Page<GuardianshipDto>> {
    return this.people.listGuardianships(toPageRequest(query), query.studentId);
  }

  @Post()
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Link a parent to a child',
    description: 'The parent may see that child from their next request.',
  })
  @ApiErrorResponse(HttpStatus.BAD_REQUEST, BODY_INVALID)
  @ApiErrorResponse(HttpStatus.NOT_FOUND, 'The parent or student does not exist in this school.')
  @ApiErrorResponse(HttpStatus.CONFLICT, 'That parent is already linked to that child.')
  @ApiItemResponse(GuardianshipDto, 'Guardianship created.', HttpStatus.CREATED)
  create(@Body() input: CreateGuardianshipDto): Promise<GuardianshipDto> {
    return this.people.addGuardianship(input);
  }

  @Delete(':id')
  @RequiresPermission(Permission.PeopleManage)
  @ApiOperation({
    summary: 'Unlink a parent from a child',
    description: 'The parent loses access to that child from their next request.',
  })
  @ApiErrorResponse(HttpStatus.NOT_FOUND, NOT_IN_SCHOOL('guardianship'))
  @ApiEmptyResponse('Guardianship removed.')
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    await this.people.removeGuardianship(id);
  }
}
